!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  host: cwcc.compuware.com
  port: 16196
  runtimeConfig: ispw
  stream: GITDEMO1
  application: GITD
  pathMappings:
  - path: "**/Sources/**"
    types:
    - cics: 'Yes'
      fileExtension: ccb
      ispwType: COB
      progType: 'Yes'
  - path: "**/Sources/**"
    types:
    - fileExtension: cbl
      ispwType: COB
      progType: 'Yes'
  - path: "**/Sources/**"
    types:
    - fileExtension: cpy
      ispwType: COPY
  - path: "**/Sources/**"
    types:
    - fileExtension: incl
      ispwType: INCL
  - path: "**/Sources/**"
    types:
    - fileExtension: jcl
      ispwType: JOB
  - path: "**/Sources/**"
    types:
    - fileExtension: pli
      ispwType: PLI
      progType: 'Yes'
